version: '3.8'

services:
  client:
    image: ${REGISTRY}/lumidoc/client:staging
    restart: unless-stopped

  server:
    image: ${REGISTRY}/lumidoc/server:staging
    restart: unless-stopped
    environment:
      - ENVIRONMENT=staging
      - DEBUG=false

  celery:
    image: ${REGISTRY}/lumidoc/celery:staging
    restart: unless-stopped
    environment:
      - ENVIRONMENT=staging

  nginx:
    image: ${REGISTRY}/lumidoc/nginx:staging
    restart: unless-stopped
